### ISSUE TITLE
Non-middleware version

### ISSUE THREAD

**Issue by runexec** [weavejester/ring-anti-forgery#14]
I made a non-middleware version because I wasn't aware of this project. Because it's not middleware it won't break POST request for non-browser based webservices. Would you please take a look and tell me what you think? Thanks. https://github.com/runexec/ring-csrf/tree/master/ring-csrf

**Comment by weavejester** [comment]
It appears as if this project has since been deleted. Also, you know you can apply middleware selectively, right?

**Comment by runexec** [comment]
Sorry for the late reply. I'll be writing a new one with the same functionality. I'll contact you when it's complete

**Comment by weavejester** [comment]
Closing this issue; please reopen on new repository location if this is still relevant.

https://github.com/ring-clojure/ring-anti-forgery
